### ISSUE TITLE
cannot use makeMQTTout (type func(beat.Info, *outputs.Stats, *common.Config) (outputs.Group, error)) as type outputs.Factory in argument to outputs.RegisterType

### ISSUE THREAD

**Issue by pvandervelde** [sidleal/mqttout#2]
I'm trying to add mqttout to filebeat. Based on the linked post on the elasticsearch forums I've made a `main.go` file which looks like

	package main

	import (
		"os"

		_ "github.com/sidleal/mqttout"

		"github.com/elastic/beats/filebeat/beater"
		"github.com/elastic/beats/libbeat/beat"
	)

	func main() {
		if err := cmd.RootCmd.Execute(); err != nil {
			os.Exit(1)
		}
	}

Using the 6.3 branch for beats when I run `go build` (using go 1.10.3) I get two errors

    ..\..\sidleal\mqttout\mqtt.go:108:17: not enough arguments in call to st.WriteError
        have ()
        want (error)

and 

    ..\..\sidleal\mqttout\mqtt.go:15:23: cannot use makeMQTTout (type func(beat.Info, *outputs.Stats, *common.Config) (outputs.Group, error)) as type outputs.Factory in argument to outputs.RegisterType

I fixed the first error by changing `st.WriteError()` to `st.WriteError(token.Error())` but I have no idea what the second error means. I have not been able to find any documents on the internet telling me what the problem is so I'm guessing it's either that I'm using an incorrect version of Go, there is a dependency I'm missing or Go has changed things which means the code isn't correct anymore?

**Comment by sidleal** [comment]
Hi Petrik, thanks for the feedback.

It seems that some things have changed in the beats output structure. I changed the code a little bit and now it's building. But I could not test it, because I lost my mqtt environment. I'll appreciate if you could continue with the tests.
 
See my last commit. And my main.go is just:
````
import (
	"os"

	_ "github.com/sidleal/mqttout"

	"github.com/elastic/beats/filebeat/cmd"
)
````

**Comment by pvandervelde** [comment]
@sidleal Thanks for the super quick fix. I've got a RabbitMQ server on a VM and the first tests worked. I will be doing some more testing but for now it's looking good. Thanks heaps!

**Comment by pvandervelde** [comment]
I've had a windows VM with a modified FileBeat sending messages to RabbitMQ through MQTT for about 6 hours constantly now. I'm pretty happy with how it works. I'll run some longer duration tests if I can find a good time window. My `main.go` file for FileBeat is here: https://github.com/pvandervelde/filebeat.mqtt if you're interested.

Again thanks heaps for the quick fix!

**Comment by sidleal** [comment]
I'm happy to know that! Thank you.
