### ISSUE TITLE
cannot use makeMQTTout (type func(beat.Info, outputs.Observer, *common.Config) (outputs.Group, error)) as type outputs.Factory in argument to outputs.RegisterType - Part II

### ISSUE THREAD

**Issue by pvandervelde** [sidleal/mqttout#3]
Last year I made a [version of Filebeat with an MQTT output](https://github.com/pvandervelde/filebeat.mqtt) for which I used this library. That specific build has been working just fine. However today I tried rebuilding it only to get the same error as last time.

My `main.go` looks like

    package main

    import (
        "os"

        _ "github.com/sidleal/mqttout"

        "github.com/elastic/beats/filebeat/cmd"
    )

    func main() {
        if err := cmd.RootCmd.Execute(); err != nil {
            os.Exit(1)
        }
    }

And my `Gopkg.toml` looks like

    [[constraint]]
    name = "github.com/elastic/beats"
    version = "6.3.1"

    [[constraint]]
    branch = "master"
    name = "github.com/sidleal/mqttout"

    [prune]
    go-tests = true
    unused-packages = true

I suspect that the issue this time is caused either by the fact that the MQTT library isn't locked down or the beats library isn't locked down.

Can somebody give me some advice on how to allow me to build again?

**Comment by sidleal** [comment]
Hi Petrik, it seems that the interface was changed again. I implemented a new method in the file mqtt.go, could you test again with this version?

https://github.com/sidleal/mqttout/blob/master/mqtt.go#L136

````
func (out *mqttOutput) String() string {
	return "MQTT"
}
````

**Comment by pvandervelde** [comment]
@sidleal I'll rebuild and test today and let you know if it works. Also is there a way for me to lock the dependencies to a specific version so that I can build it even if any of the dependencies (or the dependencies of the dependencies) change?

**Comment by sidleal** [comment]
I must confess that I have to study better the golang dependency manager. Until now I only saved the entire "vendor" sub-folder with my code, to freeze the dependencies.

**Comment by pvandervelde** [comment]
I've got a test running at the moment with a modified Filebeat and a modified Winlogbeat. Both seem to work but I'd like to keep the test running overnight to see if anything changes.

As for locking the dependencies, my repo's have a [`gopkg.toml`](https://github.com/pvandervelde/filebeat.mqtt/blob/master/Gopkg.toml) file which seems to work. But I know even less about Go than you do so best not take my word for it :)

**Comment by sidleal** [comment]
Nice :-)

**Comment by pvandervelde** [comment]
Ok so both ran fine overnight and they're still pushing messages to the queue. I'd say it's probably ok. I have currently linked both repos to the last commit on your master branch but let me know if you want to do any more changes / create tags etc.. If not I will release my changes

And thanks for fixing things quickly again!

**Comment by sidleal** [comment]
Hi Petrik. Great news! I created a release 1.0.0 with this last commit, hopping that it helps to manage the dependencies (still have to study it more). Thank you for the feedback and tests.

**Comment by pvandervelde** [comment]
Awesome thanks!

**Comment by antonzajtsev** [comment]
Hello, I have the latest version of code but same mistake is dropping out. Could you please help me?

**Comment by sidleal** [comment]
Hi @antonzajtsev, which beats version are you testing in?

**Comment by antonzajtsev** [comment]
Beats version 7.1.1

**Comment by sidleal** [comment]
Interface changed again. I've just released a new update tested in the last beats version. 

@antonzajtsev, Thanks for the feedback. If it does not work with 7.1.1, please upgrade to 7.4.2.

the only change was in mqtt.go:
````
#Before 
func makeMQTTout(
	beat beat.Info,
	observer outputs.Observer,
	cfg *common.Config,
) (outputs.Group, error) {

#After 
func makeMQTTout(
	_ outputs.IndexManager,
	beat beat.Info,
	observer outputs.Observer,
	cfg *common.Config,
) (outputs.Group, error) {

````
